name: Node CI

on:
  push:
    branches: 
      - master

  pull_request:
    branches: 
      - master

jobs:
  build:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        rm -rf node_modules
        # We don't have package-lock file in the repo so will be installing
        # with good ol `install` and not `ci`
        # npm ci
        npm install

    - name: Run test suite
      run: npm run test
